version: "3.8"

services:
  m2rs-discovery-service:
    container_name: m2rs-discovery-service
    build: ./m2rs-discovery-service/.
    networks:
      - my-network
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://m2rs-discovery-service:8761/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  m2rs-config-service:
    container_name: m2rs-config-service
    build: ./m2rs-config-service/.
    networks:
      - my-network
    ports:
      - "8888:8888"
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
      config-path: /root/home/config
    volumes:
      - "/Users/hwpark/Documents/hwpark-workspace/m2rs/config:/root/home/config"
    depends_on:
      m2rs-discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://m2rs-config-service:8888/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  m2rs-api-gateway-service:
    container_name: m2rs-api-gateway-service
    build: ./m2rs-api-gateway-service/.
    networks:
      - my-network
    ports:
      - "8000:8000"
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
      config-server-url: http://m2rs-config-service:8888
    depends_on:
      m2rs-config-service:
        condition: service_healthy
  m2rs-user-service:
    container_name: m2rs-user-service
    build: ./m2rs-user-service/.
    networks:
      - my-network
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
      config-server-url: http://m2rs-config-service:8888
    depends_on:
      m2rs-config-service:
        condition: service_healthy

networks:
  my-network:
    name: m2rs-network
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.18.0.1
          subnet: 172.18.0.0/16

