version: "3.8"

services:
  m2rs-discovery-service:
    container_name: m2rs-discovery-service
    build: ./m2rs-discovery-service/.
    ports:
      - "8761:8761"
      - "15005:5005"
  m2rs-api-gateway-service:
    container_name: m2rs-api-gateway-service
    build: ./m2rs-api-gateway-service
    ports:
      - "8000:8000"
      - "15006:5005"
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
    depends_on:
      - m2rs-discovery-service
  m2rs-config-service:
    container_name: m2rs-config-service
    build: ./m2rs-config-service
    ports:
      - "8888:8888"
      - "15007:5005"
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
      config-path: /root/home/config
    volumes:
      - "/Users/hwpark/Documents/hwpark-workspace/m2rs/config:/root/home/config"
    depends_on:
      - m2rs-discovery-service
  m2rs-user-service:
    container_name: m2rs-config-service
    build: ./m2rs-user-service
    ports:
      - "15007:5005"
    environment:
      eureka-server-url: http://m2rs-discovery-service:8761/eureka
      config-server-url: http://m2rs-config-service:8888
    depends_on:
      - m2rs-config-service


networks:
  my-network:
    name: m2rs-network
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.18.0.1
          subnet: 172.18.0.0/16

