## db config
apiVersion: v1
kind: ConfigMap
metadata:
  name: m2rs-db-config
data:
  MARIADB_ROOT_PASSWORD: hwpark12345!
---
## db
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: m2rs-db
  name: m2rs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2rs-db
  template:
    metadata:
      labels:
        app: m2rs-db
    spec:
      containers:
        - name: m2rs-db
          images: mariadb
          envForm:
            - configMapRef:
                name: m2rs-db-config
---
## zipkin
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: m2rs-zipkin
  name: m2rs-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2rs-zipkin
  template:
    metadata:
      labels:
        app: m2rs-zipkin
    spec:
      containers:
        - name: m2rs-zipkin
          images: openzipkin/zipkin
---
## service discovery

