## db config
apiVersion: v1
kind: ConfigMap
metadata:
  name: m2rs-db-config
data:
  MARIADB_ROOT_PASSWORD: "12345"
---
## config service
apiVersion: v1
kind: ConfigMap
metadata:
  name: m2rs-common-config
data:
  EUREKA_SERVER_URL: "http://m2rs-discovery-service-domain:8761/eureka"
  CONFIG_GIT_URI: "https://github.com/bob-park/meeting-room-reservation-system-config.git"