# server
server:
  port: 8000

# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - httptrace

# spring
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service # login
          uri: lb://user-service
          predicates:
            - Path=/user-service/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user_service # company 조회
          uri: lb://user-service
          predicates:
            - Path=/user-service/company/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service # user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-server-url}

logging:
  level:
    root: info
    web: debug
    com.m2rs: debug