# server
server:
  port: 8888

# spring
spring:
  application:
    name: config-service
  ## Local file system
#  profiles:
#    active: native
  cloud:
    config:
      server:
        ## Local file system
#        native:
#          search-locations:
#            - file:${config-path}
        git:
          uri: ${CONFIG_GIT_URI}

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

## management
management:
  endpoints:
    web:
      exposure:
        include:
          - health

## logging
logging:
  level:
    web: debug